services:
  agent:
    image: hnquangit/redteam-attack-engine:latest
    container_name: cyberrange-dast-agent
    env_file:
      - .env
    environment:
      TARGET_URL: ${TARGET_URL:-http://127.0.0.1:80}
      HOST_HEADER: ${HOST_HEADER:-vulnerable.cyberrange.local}
      ATTACK_PROFILE: ${ATTACK_PROFILE:-stealth}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-2.5-flash}
      QDRANT_URL: ${QDRANT_URL:-http://qdrant:6333}
      QDRANT_API_KEY: ${QDRANT_API_KEY:-}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION:-waf_payloads}
      QDRANT_DENSE_MODEL: ${QDRANT_DENSE_MODEL:-jinaai/jina-embeddings-v2-base-code}
      QDRANT_SPARSE_MODEL: ${QDRANT_SPARSE_MODEL:-Qdrant/bm25}
      QDRANT_DENSE_VECTOR_NAME: ${QDRANT_DENSE_VECTOR_NAME:-dense}
      QDRANT_SPARSE_VECTOR_NAME: ${QDRANT_SPARSE_VECTOR_NAME:-sparse}
    command:
      - python
      - main.py
      - --target-url
      - ${TARGET_URL:-http://127.0.0.1:80}
      - --host-header
      - ${HOST_HEADER:-vulnerable.cyberrange.local}
      - --attack-profile
      - ${ATTACK_PROFILE:-stealth}
      - --client-ip
      - ${LAB_CLIENT_IP:-104.38.105.84}
    restart: unless-stopped

volumes:
  qdrant_data:
